### ISSUE TITLE
Add as maintainer

### ISSUE THREAD

**Issue by timkpaine** [conda-forge/ipyregulartable-feedstock#1]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by bollwyvl** [comment]
Added, created #2 to update the CODEOWNERS and README...

**Comment by bollwyvl** [comment]
Should be all fixed up now! Welcome aboard!
